kingdoms:
- Ixa
- Brol
- Myra
kingdomblocks:
  Ixa: wool:4
  Brol: wool:1
  Myra: wool:14
build_cost: 50
break_cost: 30
use_cost: 10
use_materials:
- chest
- wood_door
scoreboard:
  title: '&c&l Informatie '
  board:
  - '&7Chatkanaal:'
  - '&f%kingdomName%'
  - '    '
  - '&7Influence:'
  - '&f%points%'
  - '  '
  - '&7Online:'
  - '&f%online%'
  - '   '
  - '&7Locatie:'
  - '&f[%loc%&f]'
friendly-fire:
- jemoeder
scoreboard_war:
  title: '&c&l Oorlog '
  board:
  - '&7Duur'
  - '&f%duur%'
  - ' '
  - '&7Deelnemers: &f%deelnemers%'
  - '&7Gesneuveld: &f%gesneuveld%'
  - '   '
  - '&7Kills:'
  kills: '%kingdom%:&7 %kills%'
  kothl1: '        '
  kothl2: '&7Koths:'
  koth: '&f%koth%: %time%'
scoreboard_staff:
  title: '&c&l Staffmode '
  board:
  - '&7Zichtbaar:'
  - '&f%zichtbaarheid%'
  - '    '
  - '&7GameMode:'
  - '&fCreative'
  - ' '
  - '&7Chat Mode:'
  - '&fPublic'
  - '  '
  - '&7Staff online:'
  - '&f%staff_c%'
colors:
  Ixa: '&eIxa'
  Brol: '&6Brol'
  Myra: '&2Myra'
ranks:
- burger
- ridder1
- ridder2
- ridder3
- hertog
- koning
rank:
  burger:
    prefix: '&r'
  ridder1:
    prefix: '&7[&fRidder &6I&7]'
  ridder2:
    prefix: '&7[&fRidder &6II&7]'
  ridder3:
    prefix: '&7[&fRidder &6III&7]'
  hertog:
    prefix: '&7[&2Hertog&7]'
  koning:
    prefix: '&7[&6Koning&7]'
messages:
  kill: '&7[%player_kingdom%&7] %player%&7 is verwond door &7[%killer_kingdom%&7]
    %killer%'
high_perms_nmr: 3
high_perms:
- essentials.ban
blacklist:
- poep
- chinees
kothreward:
  item: wood
  amount: 1
  itemData: 0
  name: '&8reward'
  lore: []
crates:
- test
crate:
  test:
    rewards:
    - '1'
    - '1'
    - '2'
    title: '&7Test crate'
    lore:
    - '&7Test'
    reward:
      '1':
        type: wood
        amount: 1
        data: 1
        title: '&7Test reward'
        lore:
        - '&7Test'
      '2':
        type: stone
        amount: 1
        data: 1
        title: '&7Test reward'
        lore:
        - '&7Stoned'
leaderboard:
  format_top: '&7---------'
  format: '&8%kingdom%: %kills%'
  format_bottom: '&7---------'
stats:
  format_top: '&7----- statastieken van %player%'
  format_deaths: '&7Deaths: %deaths%'
  format_kills: '&7Kills: %kills%'
cant_hit_because_ally: '&cJe kan &6%player% &cniet slaan omdat hij een ally is.'

